//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Common/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Fighting"",
            ""id"": ""1743223c-2511-42a3-b96b-b5d7fc9dff5c"",
            ""actions"": [
                {
                    ""name"": ""FourDirections"",
                    ""type"": ""Value"",
                    ""id"": ""5fc13f59-f0c2-494e-8c95-5b41ea036bd0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""975803be-6702-4356-934b-3e47a77797e7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NormalMove"",
                    ""type"": ""Button"",
                    ""id"": ""a8f9ef1c-9c37-4b5c-864f-ff7df0d10268"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialMove1"",
                    ""type"": ""Button"",
                    ""id"": ""b961b71c-0689-4b88-820c-dbbbe142042b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialMove2"",
                    ""type"": ""Button"",
                    ""id"": ""d6c5efb2-c594-43d4-97ef-6393ea7ec68a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Value"",
                    ""id"": ""bebe953d-2feb-4451-abb3-08d2e9315315"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Ultimate"",
                    ""type"": ""Button"",
                    ""id"": ""fbe694de-eeca-4bd1-92f2-a46f16a27684"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""511d03ee-26f7-441a-87f6-63964202ea16"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourDirections"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8fa46373-2952-4ad1-90ec-73d54007e446"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""346e1ab1-c3d0-459e-bb9d-a9cfa92c1d21"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""13abc0fa-0902-4777-ad23-bb01e39e205b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bcd028b8-3898-4b1f-95ae-6b61effc708f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a61e1341-4f84-4d9a-82b4-3647abf50932"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2e34a3b-ad73-45a6-9a12-575539ed1a97"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fb4583b-8b96-4d2c-84bc-af48c2b13bbe"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/hat"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76d37689-0fb1-4c9f-b7c2-e1f8dac62568"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5174c2d4-0a63-4725-87f3-451ff65e0599"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93a61797-950e-4716-be91-7901a64d828a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ba72158-d196-425b-a478-34f8d7fbcdf3"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba1b6a63-cdf7-4d53-b41b-c16b272dbd86"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f56beb85-4219-4281-9967-a0533237f25c"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""NormalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68665d76-c5ee-40a7-b855-1639ea888000"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""NormalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1f6a134-4870-4588-8e13-a80b0e73e599"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""NormalMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""036d6fe3-e698-4e6b-bfba-7402436dd3a0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""SpecialMove1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74d990ce-b33a-4ed6-a099-71a212c5c338"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""SpecialMove1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53cc3d7b-34f2-453b-b528-86471cb6869a"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""SpecialMove1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65e88e72-6e27-42aa-9a83-0975000235da"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""SpecialMove2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""704a8452-916c-4e33-96fc-d93ba90b5828"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""SpecialMove2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3c8105d-c976-4fc5-9a74-e0da8d2f693f"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""SpecialMove2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe8715a8-c5fc-430c-9f37-2d8a00fa8404"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ed34ff5-fb39-4dfa-95ec-4814ba70c6eb"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98a73a8c-1097-4e57-8d47-7dadbab13bd1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3867e9d-ee07-42ed-a1b1-44caad00de4f"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6aefc32-12b0-41cf-a85c-ce87c675a5bd"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""Ultimate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Other"",
            ""id"": ""4aff387b-d19c-4067-8d2d-b8d096d936f9"",
            ""actions"": [
                {
                    ""name"": ""Accept"",
                    ""type"": ""Button"",
                    ""id"": ""6cbb79da-b8f2-4b0b-b88c-552e76a05bbe"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""e8308d40-1d7a-4691-911c-9b725420acbd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FourDirections"",
                    ""type"": ""Value"",
                    ""id"": ""cbb8f186-c055-4ae0-a2b5-7b3f2f9a1ab4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""d43fcaf9-6615-4214-881b-9ee11b5eaf4d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d35ab960-da06-4a30-8f84-3345047ba47e"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/hat"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b9f6c7a-86fa-4c55-819e-663e094081db"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4404fed3-fc7b-4fd8-be12-f2abf22776b3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39b356a5-8f93-49d9-9956-d2a5488d73c4"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""631a498e-e32e-447d-be69-8e516e0ca432"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FourDirections"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""27231493-f426-44df-b6b8-77785cc09488"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2a84e99b-2154-4748-a3f2-be8a5bf44c59"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""13e1892f-bf01-46d7-bbd4-c3ba94128b09"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""03d0ad55-7c33-4b54-8e4b-dafe2fe94094"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""FourDirections"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c827deae-9cb4-435b-8044-655510c61b79"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d71d7d2d-480b-41ba-b749-e086b77baef7"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""119e2255-bd25-4422-a6b3-dfc01f511c92"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Accept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e03e2bd9-290b-429d-82fa-3ccc808517b3"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3446ce2-ab6e-49f1-812b-67f0b044d19f"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b347af7-b60b-4d01-8b62-75501197d34d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""930bcc82-9fa6-4e75-9533-d6a4b0328ae3"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";KeyboardScheme"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b4f84c4-11c6-4e2f-8dd7-77e8d07c089a"",
                    ""path"": ""<HID::HORI CO.,LTD. HORIPAD 4 >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";HoriPadScheme"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95a3bb70-6eb5-4dc6-848c-6e95ce226101"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";GamepadScheme"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardScheme"",
            ""bindingGroup"": ""KeyboardScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""GamepadScheme"",
            ""bindingGroup"": ""GamepadScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""HoriPadScheme"",
            ""bindingGroup"": ""HoriPadScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Fighting
        m_Fighting = asset.FindActionMap("Fighting", throwIfNotFound: true);
        m_Fighting_FourDirections = m_Fighting.FindAction("FourDirections", throwIfNotFound: true);
        m_Fighting_Jump = m_Fighting.FindAction("Jump", throwIfNotFound: true);
        m_Fighting_NormalMove = m_Fighting.FindAction("NormalMove", throwIfNotFound: true);
        m_Fighting_SpecialMove1 = m_Fighting.FindAction("SpecialMove1", throwIfNotFound: true);
        m_Fighting_SpecialMove2 = m_Fighting.FindAction("SpecialMove2", throwIfNotFound: true);
        m_Fighting_Guard = m_Fighting.FindAction("Guard", throwIfNotFound: true);
        m_Fighting_Ultimate = m_Fighting.FindAction("Ultimate", throwIfNotFound: true);
        // Other
        m_Other = asset.FindActionMap("Other", throwIfNotFound: true);
        m_Other_Accept = m_Other.FindAction("Accept", throwIfNotFound: true);
        m_Other_Cancel = m_Other.FindAction("Cancel", throwIfNotFound: true);
        m_Other_FourDirections = m_Other.FindAction("FourDirections", throwIfNotFound: true);
        m_Other_Interact = m_Other.FindAction("Interact", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Fighting.enabled, "This will cause a leak and performance issues, PlayerInputActions.Fighting.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Other.enabled, "This will cause a leak and performance issues, PlayerInputActions.Other.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Fighting
    private readonly InputActionMap m_Fighting;
    private List<IFightingActions> m_FightingActionsCallbackInterfaces = new List<IFightingActions>();
    private readonly InputAction m_Fighting_FourDirections;
    private readonly InputAction m_Fighting_Jump;
    private readonly InputAction m_Fighting_NormalMove;
    private readonly InputAction m_Fighting_SpecialMove1;
    private readonly InputAction m_Fighting_SpecialMove2;
    private readonly InputAction m_Fighting_Guard;
    private readonly InputAction m_Fighting_Ultimate;
    public struct FightingActions
    {
        private @PlayerInputActions m_Wrapper;
        public FightingActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FourDirections => m_Wrapper.m_Fighting_FourDirections;
        public InputAction @Jump => m_Wrapper.m_Fighting_Jump;
        public InputAction @NormalMove => m_Wrapper.m_Fighting_NormalMove;
        public InputAction @SpecialMove1 => m_Wrapper.m_Fighting_SpecialMove1;
        public InputAction @SpecialMove2 => m_Wrapper.m_Fighting_SpecialMove2;
        public InputAction @Guard => m_Wrapper.m_Fighting_Guard;
        public InputAction @Ultimate => m_Wrapper.m_Fighting_Ultimate;
        public InputActionMap Get() { return m_Wrapper.m_Fighting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FightingActions set) { return set.Get(); }
        public void AddCallbacks(IFightingActions instance)
        {
            if (instance == null || m_Wrapper.m_FightingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FightingActionsCallbackInterfaces.Add(instance);
            @FourDirections.started += instance.OnFourDirections;
            @FourDirections.performed += instance.OnFourDirections;
            @FourDirections.canceled += instance.OnFourDirections;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @NormalMove.started += instance.OnNormalMove;
            @NormalMove.performed += instance.OnNormalMove;
            @NormalMove.canceled += instance.OnNormalMove;
            @SpecialMove1.started += instance.OnSpecialMove1;
            @SpecialMove1.performed += instance.OnSpecialMove1;
            @SpecialMove1.canceled += instance.OnSpecialMove1;
            @SpecialMove2.started += instance.OnSpecialMove2;
            @SpecialMove2.performed += instance.OnSpecialMove2;
            @SpecialMove2.canceled += instance.OnSpecialMove2;
            @Guard.started += instance.OnGuard;
            @Guard.performed += instance.OnGuard;
            @Guard.canceled += instance.OnGuard;
            @Ultimate.started += instance.OnUltimate;
            @Ultimate.performed += instance.OnUltimate;
            @Ultimate.canceled += instance.OnUltimate;
        }

        private void UnregisterCallbacks(IFightingActions instance)
        {
            @FourDirections.started -= instance.OnFourDirections;
            @FourDirections.performed -= instance.OnFourDirections;
            @FourDirections.canceled -= instance.OnFourDirections;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @NormalMove.started -= instance.OnNormalMove;
            @NormalMove.performed -= instance.OnNormalMove;
            @NormalMove.canceled -= instance.OnNormalMove;
            @SpecialMove1.started -= instance.OnSpecialMove1;
            @SpecialMove1.performed -= instance.OnSpecialMove1;
            @SpecialMove1.canceled -= instance.OnSpecialMove1;
            @SpecialMove2.started -= instance.OnSpecialMove2;
            @SpecialMove2.performed -= instance.OnSpecialMove2;
            @SpecialMove2.canceled -= instance.OnSpecialMove2;
            @Guard.started -= instance.OnGuard;
            @Guard.performed -= instance.OnGuard;
            @Guard.canceled -= instance.OnGuard;
            @Ultimate.started -= instance.OnUltimate;
            @Ultimate.performed -= instance.OnUltimate;
            @Ultimate.canceled -= instance.OnUltimate;
        }

        public void RemoveCallbacks(IFightingActions instance)
        {
            if (m_Wrapper.m_FightingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFightingActions instance)
        {
            foreach (var item in m_Wrapper.m_FightingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FightingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FightingActions @Fighting => new FightingActions(this);

    // Other
    private readonly InputActionMap m_Other;
    private List<IOtherActions> m_OtherActionsCallbackInterfaces = new List<IOtherActions>();
    private readonly InputAction m_Other_Accept;
    private readonly InputAction m_Other_Cancel;
    private readonly InputAction m_Other_FourDirections;
    private readonly InputAction m_Other_Interact;
    public struct OtherActions
    {
        private @PlayerInputActions m_Wrapper;
        public OtherActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Accept => m_Wrapper.m_Other_Accept;
        public InputAction @Cancel => m_Wrapper.m_Other_Cancel;
        public InputAction @FourDirections => m_Wrapper.m_Other_FourDirections;
        public InputAction @Interact => m_Wrapper.m_Other_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Other; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OtherActions set) { return set.Get(); }
        public void AddCallbacks(IOtherActions instance)
        {
            if (instance == null || m_Wrapper.m_OtherActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OtherActionsCallbackInterfaces.Add(instance);
            @Accept.started += instance.OnAccept;
            @Accept.performed += instance.OnAccept;
            @Accept.canceled += instance.OnAccept;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @FourDirections.started += instance.OnFourDirections;
            @FourDirections.performed += instance.OnFourDirections;
            @FourDirections.canceled += instance.OnFourDirections;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IOtherActions instance)
        {
            @Accept.started -= instance.OnAccept;
            @Accept.performed -= instance.OnAccept;
            @Accept.canceled -= instance.OnAccept;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @FourDirections.started -= instance.OnFourDirections;
            @FourDirections.performed -= instance.OnFourDirections;
            @FourDirections.canceled -= instance.OnFourDirections;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IOtherActions instance)
        {
            if (m_Wrapper.m_OtherActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOtherActions instance)
        {
            foreach (var item in m_Wrapper.m_OtherActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OtherActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OtherActions @Other => new OtherActions(this);
    private int m_KeyboardSchemeSchemeIndex = -1;
    public InputControlScheme KeyboardSchemeScheme
    {
        get
        {
            if (m_KeyboardSchemeSchemeIndex == -1) m_KeyboardSchemeSchemeIndex = asset.FindControlSchemeIndex("KeyboardScheme");
            return asset.controlSchemes[m_KeyboardSchemeSchemeIndex];
        }
    }
    private int m_GamepadSchemeSchemeIndex = -1;
    public InputControlScheme GamepadSchemeScheme
    {
        get
        {
            if (m_GamepadSchemeSchemeIndex == -1) m_GamepadSchemeSchemeIndex = asset.FindControlSchemeIndex("GamepadScheme");
            return asset.controlSchemes[m_GamepadSchemeSchemeIndex];
        }
    }
    private int m_HoriPadSchemeSchemeIndex = -1;
    public InputControlScheme HoriPadSchemeScheme
    {
        get
        {
            if (m_HoriPadSchemeSchemeIndex == -1) m_HoriPadSchemeSchemeIndex = asset.FindControlSchemeIndex("HoriPadScheme");
            return asset.controlSchemes[m_HoriPadSchemeSchemeIndex];
        }
    }
    public interface IFightingActions
    {
        void OnFourDirections(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnNormalMove(InputAction.CallbackContext context);
        void OnSpecialMove1(InputAction.CallbackContext context);
        void OnSpecialMove2(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnUltimate(InputAction.CallbackContext context);
    }
    public interface IOtherActions
    {
        void OnAccept(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnFourDirections(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
}
