behaviors:
  Lancer_Easy:                     
    trainer_type: ppo            
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128          
      num_layers: 2
    reward_signals:
<<<<<<< HEAD
      extrinsic:
        gamma: 0.75
=======
      extrinsic:                 
        gamma: 0.99
>>>>>>> 5120a4b11980d8433d5ee9514b5d1bf021675f04
        strength: 1.0
    max_steps: 1000000            
    time_horizon: 64
    summary_freq: 10000