behaviors:
  Lancer_Easy:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 81920
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    max_steps: 20_000_000
    time_horizon: 64
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 50000
      swap_steps: 2000
      window: 10